### ISSUE TITLE
Referenced github project not present anymore

### ISSUE THREAD

**Issue by bouviervj** [cinderblocks/conan-uriparser#1]
It seems that the referenced github project is not valid anymore in conanfile.py - source definition - turns out that you can now use the standard project and change the replace part in source definition - it doesn't match the replaced string anymore. As well as you should also delete the cloned repo before clone, else 'conan source .' works only once (can't clone on the same directory path)

**Comment by cinderblocks** [comment]
Thanks for the heads up! Not entirely sure what happened to my uriparser repo, but I will get this fixed shortly.

**Comment by cinderblocks** [comment]
Replaced with canonical repo url, download zip of specific version instead of building HEAD
